-- CityRunner — leaderboard schema and row-level security.
--
-- Run this in the Supabase SQL editor when the project is created.
--
-- THE SECURITY MODEL, STATED PLAINLY:
-- The anon key shipped in the game is public. Anyone can read it out of the
-- bundle and call this database directly. Row-level security is therefore the
-- ONLY control protecting this data — not the client code, not obscurity.
-- Every policy below assumes a hostile caller holding a valid anon key.

-- ---------------------------------------------------------------------------
-- Players: anonymous identities. No email, no real name, no device fingerprint.
-- ---------------------------------------------------------------------------
create table if not exists players (
  id           uuid primary key,
  display_name text not null check (display_name ~ '^[A-Za-z]{3,40}[0-9]{2}$'),
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

comment on table players is
  'Anonymous player identities. display_name is generated by the client from '
  'curated word lists; the CHECK constraint enforces that shape server-side so '
  'free-text names can never enter the system.';

-- ---------------------------------------------------------------------------
-- Scores
-- ---------------------------------------------------------------------------
create table if not exists scores (
  id          bigint generated always as identity primary key,
  player_id   uuid not null references players (id) on delete cascade,
  mode        text not null check (mode in ('run', 'daily')),
  city_id     text check (city_id in ('nyc', 'paris', 'london', 'rome')),
  level       smallint check (level between 1 and 3),
  day         date,
  seed        bigint,
  score       integer not null check (score >= 0 and score <= 5000000),
  duration_ms integer not null check (duration_ms >= 3000),
  created_at  timestamptz not null default now()
);

create index if not exists scores_daily_idx on scores (mode, day, score desc);
create index if not exists scores_city_idx  on scores (mode, city_id, level, score desc);
create index if not exists scores_player_idx on scores (player_id, created_at desc);

-- One daily-challenge score per player per day. Enforced by the database, not
-- by the client, because the client cannot be trusted to enforce anything.
create unique index if not exists scores_one_daily_per_player
  on scores (player_id, day) where mode = 'daily';

-- ---------------------------------------------------------------------------
-- Plausibility check, server-side.
-- Mirrors maxPlausibleScore() in src/core/scores.js. The client check is a
-- courtesy; THIS is the control.
-- ---------------------------------------------------------------------------
create or replace function is_plausible_score(score integer, duration_ms integer)
returns boolean language sql immutable as $$
  select score <= ceil(
    2 * (22 * (duration_ms / 1000.0) + 0.125 * power(duration_ms / 1000.0, 2))
    + 200 * (duration_ms / 1000.0)
    + 3000 + 500
  );
$$;

alter table scores add constraint scores_plausible
  check (is_plausible_score(score, duration_ms)) not valid;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
alter table players enable row level security;
alter table scores  enable row level security;

-- Leaderboards are public to read. Only id, display_name and score are ever
-- exposed through the views below.
drop policy if exists players_read on players;
create policy players_read on players for select using (true);

drop policy if exists scores_read on scores;
create policy scores_read on scores for select using (true);

-- Anyone may create their own identity row...
drop policy if exists players_insert on players;
create policy players_insert on players for insert with check (true);

-- ...but NOT rename or delete anyone (including themselves — a rename route
-- would let a caller impersonate another player's display name).
-- No update or delete policy exists, so both are denied by default.

-- Scores are insert-only. No update policy and no delete policy means a score,
-- once posted, cannot be edited or removed by any anon caller.
drop policy if exists scores_insert on scores;
create policy scores_insert on scores for insert with check (
  score >= 0
  and duration_ms >= 3000
  and is_plausible_score(score, duration_ms)
  and (mode <> 'daily' or day = (now() at time zone 'utc')::date)
);

-- ---------------------------------------------------------------------------
-- Public views — the only shape the game should read.
-- ---------------------------------------------------------------------------
create or replace view leaderboard_daily as
  select p.display_name, s.score, s.day,
         row_number() over (partition by s.day order by s.score desc) as rank
  from scores s join players p on p.id = s.player_id
  where s.mode = 'daily';

create or replace view leaderboard_city as
  select p.display_name, s.city_id, s.level, max(s.score) as score
  from scores s join players p on p.id = s.player_id
  where s.mode = 'run'
  group by p.display_name, s.city_id, s.level;

-- ---------------------------------------------------------------------------
-- Retention: UK GDPR requires a defined retention period, not "forever".
-- Schedule via pg_cron once the project exists.
-- ---------------------------------------------------------------------------
create or replace function purge_old_scores() returns void language sql as $$
  delete from scores where created_at < now() - interval '400 days';
$$;

-- Deletion route for a data-subject request. Cascades to that player's scores.
create or replace function delete_player(target uuid) returns void language sql
security definer as $$
  delete from players where id = target;
$$;
