// Visual identity for each city. Everything downstream (sky, fog, buildings,
// props, obstacles, puzzle landmarks) is driven from this table.
// Design bar: bright, saturated, golden-hour mobile-game look (Subway Surfers).
// fog color === sky glow color so distant geometry melts into the horizon glow.
export const CITIES = [
  {
    id: 'nyc', name: 'NEW YORK', flag: '🗽',
    streets: ['Broadway', '5th Avenue', 'Times Square'],
    // Crisp blue day melting into a warm golden horizon.
    sky: { top: '#2e6ad4', mid: '#7db2f2', horizon: '#ffe9b8', glow: '#ffd98e' },
    fog: 0xffd98e, fogDensity: 0.0088,
    sun: { color: 0xfff0d0, intensity: 2.4, pos: [-60, 80, -40] },
    hemi: { sky: 0xcfe2ff, ground: 0x8a7f6e, intensity: 1.05 },
    fill: { color: 0xfff0da, intensity: 1.05 },
    road: '#4a4a52', lane: '#ffd23f', sidewalk: '#b8b2a6',
    palette: ['#b0533f', '#d9c9a4', '#8fa2b8', '#c98a5a', '#a67c62', '#96a8bc'],
    trim: '#e8e0cc', roof: '#6a5a4c',
    windowLit: '#ffd98a', windowDay: '#9cc4e8', accent: '#e33636',
    storefront: ['#e33636', '#f2a516', '#2e8fd8', '#3fae5c', '#8a4fd0'],
    props: ['lamp', 'hydrant', 'billboard', 'newsstand', 'hotdog'],
    vehicle: 'taxi',
    landmarks: ['empire', 'chrysler', 'brooklyn'],
  },
  {
    id: 'paris', name: 'PARIS', flag: '🗼',
    streets: ['Champs-Élysées', 'Rue de Rivoli', 'Montmartre'],
    // Soft lavender-blue with a rosy pastel glow.
    sky: { top: '#4a6ad8', mid: '#96b4ee', horizon: '#ffd9e4', glow: '#ffc4d4' },
    fog: 0xffc4d4, fogDensity: 0.0085,
    sun: { color: 0xfff4e0, intensity: 2.2, pos: [50, 70, -50] },
    hemi: { sky: 0xe4ecff, ground: 0x9a8d7c, intensity: 1.1 },
    fill: { color: 0xfff0e4, intensity: 1.0 },
    road: '#54545c', lane: '#f0f0f0', sidewalk: '#cfc4b0',
    palette: ['#f2e6cc', '#ecdfc2', '#e8d9ba', '#f6ecd6', '#eadcbc', '#f0e2c8'],
    trim: '#fdf8ec', roof: '#5d6d7e',
    windowLit: '#ffe6b0', windowDay: '#a8c8e4', accent: '#3a6ea5',
    storefront: ['#a02438', '#1f4a8a', '#2d6b3f', '#6a3a8a', '#b8681e'],
    props: ['lamp_paris', 'awning', 'tree', 'kiosk', 'fountain'],
    vehicle: 'citroen',
    landmarks: ['eiffel', 'arc', 'louvre'],
  },
  {
    id: 'london', name: 'LONDON', flag: '🇬🇧',
    streets: ['Oxford Street', 'Abbey Road', 'Piccadilly'],
    // Fresh morning blue with a honey glow at the rooftops.
    sky: { top: '#3a70cc', mid: '#8ab4e8', horizon: '#ffe4bc', glow: '#ffd0a0' },
    fog: 0xffd0a0, fogDensity: 0.0095,
    sun: { color: 0xfff0d8, intensity: 2.2, pos: [-40, 60, -60] },
    hemi: { sky: 0xd8e4f8, ground: 0x8a8078, intensity: 1.05 },
    fill: { color: 0xffeeda, intensity: 1.05 },
    road: '#4c4c54', lane: '#f0f0f0', sidewalk: '#b0aa9e',
    palette: ['#b4553c', '#c26445', '#a84e38', '#cc7a52', '#9a5a64', '#b86a74'],
    trim: '#f6f2e8', roof: '#5a5650',
    windowLit: '#ffedbe', windowDay: '#a0c0dc', accent: '#c8102e',
    storefront: ['#c8102e', '#1c5aa8', '#2d7a44', '#d0851c', '#5a3a8a'],
    props: ['lamp_london', 'phonebox', 'postbox', 'tree', 'bunting'],
    vehicle: 'bus',
    landmarks: ['bigben', 'towerbridge', 'eye'],
  },
  {
    id: 'rome', name: 'ROME', flag: '🏛️',
    streets: ['Via del Corso', 'Via Veneto', 'Piazza Navona'],
    // Rich Mediterranean golden hour.
    sky: { top: '#4a55b8', mid: '#c890b8', horizon: '#ffcf8c', glow: '#ffb768' },
    fog: 0xffb768, fogDensity: 0.0085,
    sun: { color: 0xffe2b0, intensity: 2.6, pos: [60, 55, -45] },
    hemi: { sky: 0xffe8cc, ground: 0x9a7c5c, intensity: 1.1 },
    fill: { color: 0xffe6c4, intensity: 1.05 },
    road: '#6a6058', lane: '#e0d4bc', sidewalk: '#c4ae8e',
    palette: ['#e8a068', '#f0b078', '#d8846a', '#f6c088', '#c86a52', '#f0dcae'],
    trim: '#f8ecd4', roof: '#b0472e',
    windowLit: '#ffdda0', windowDay: '#98b8d4', accent: '#2e7d4f',
    storefront: ['#b0472e', '#2e7d4f', '#c8861e', '#8a3a5a', '#3a6a9a'],
    props: ['lamp_rome', 'column', 'arch', 'cypress', 'fountain'],
    vehicle: 'vespa',
    landmarks: ['colosseum', 'trevi', 'pantheon'],
  },
];

export const LANDMARK_NAMES = {
  empire: 'Empire State Building', chrysler: 'Chrysler Building', brooklyn: 'Brooklyn Bridge',
  eiffel: 'Eiffel Tower', arc: 'Arc de Triomphe', louvre: 'Louvre Pyramid',
  bigben: 'Big Ben', towerbridge: 'Tower Bridge', eye: 'London Eye',
  colosseum: 'Colosseum', trevi: 'Trevi Fountain', pantheon: 'Pantheon',
};
