// Visual identity for each city. Everything downstream (sky, fog, buildings,
// props, obstacles, puzzle landmarks) is driven from this table.
export const CITIES = [
  {
    id: 'nyc', name: 'NEW YORK', flag: '🗽',
    streets: ['Broadway', '5th Avenue', 'Times Square'],
    sky: { top: '#1c2e5e', mid: '#4a6bb5', horizon: '#f2a65e' },
    fog: 0x8fa3c8, fogDensity: 0.0135,
    sun: { color: 0xffe0b0, intensity: 2.6, pos: [-60, 80, -40] },
    hemi: { sky: 0xbfd4ff, ground: 0x3a3f52, intensity: 0.55 },
    road: '#2e2e34', lane: '#e8c235', sidewalk: '#9a958c',
    palette: ['#6b6f7e', '#8a8577', '#5d6b78', '#7d7268', '#4f5866', '#8f8b83'],
    windowLit: '#ffd98a', accent: '#e33636',
    props: ['lamp', 'hydrant', 'billboard', 'scaffold', 'hotdog'],
    vehicle: 'taxi',
    landmarks: ['empire', 'chrysler', 'brooklyn'],
  },
  {
    id: 'paris', name: 'PARIS', flag: '🗼',
    streets: ['Champs-Élysées', 'Rue de Rivoli', 'Montmartre'],
    sky: { top: '#3b4a8c', mid: '#8d9fd4', horizon: '#f6c8d8' },
    fog: 0xc3cbe2, fogDensity: 0.012,
    sun: { color: 0xfff0d8, intensity: 2.4, pos: [50, 70, -50] },
    hemi: { sky: 0xdde6ff, ground: 0x55504a, intensity: 0.6 },
    road: '#3a3a40', lane: '#dcdcdc', sidewalk: '#b5ac9d',
    palette: ['#d8cbb4', '#cfc2a8', '#c4b89e', '#dcd2bc', '#c9bda1', '#d2c6ae'],
    windowLit: '#ffe6b0', accent: '#3a6ea5',
    props: ['lamp_paris', 'awning', 'tree', 'kiosk', 'fountain'],
    vehicle: 'citroen',
    landmarks: ['eiffel', 'arc', 'louvre'],
  },
  {
    id: 'london', name: 'LONDON', flag: '🇬🇧',
    streets: ['Oxford Street', 'Abbey Road', 'Piccadilly'],
    sky: { top: '#2c3550', mid: '#6a7899', horizon: '#d9b08c' },
    fog: 0x9aa4b5, fogDensity: 0.015,
    sun: { color: 0xffe8cc, intensity: 2.0, pos: [-40, 60, -60] },
    hemi: { sky: 0xc5cede, ground: 0x46424a, intensity: 0.6 },
    road: '#33333a', lane: '#d8d8d8', sidewalk: '#8e8a84',
    palette: ['#8a4a3a', '#9c5a45', '#7a4436', '#a8674f', '#6e4a52', '#96555f'],
    windowLit: '#ffedbe', accent: '#c8102e',
    props: ['lamp_london', 'phonebox', 'postbox', 'tree', 'bunting'],
    vehicle: 'bus',
    landmarks: ['bigben', 'towerbridge', 'eye'],
  },
  {
    id: 'rome', name: 'ROME', flag: '🏛️',
    streets: ['Via del Corso', 'Via Veneto', 'Piazza Navona'],
    sky: { top: '#40407e', mid: '#b586a8', horizon: '#ffb267' },
    fog: 0xd4b394, fogDensity: 0.012,
    sun: { color: 0xffd9a0, intensity: 2.8, pos: [60, 55, -45] },
    hemi: { sky: 0xffe0c0, ground: 0x5a4a3c, intensity: 0.65 },
    road: '#57504a', lane: '#c9beac', sidewalk: '#a89880',
    palette: ['#c98a5b', '#d49a66', '#b87e52', '#dba873', '#c2854f', '#cf9260'],
    windowLit: '#ffddA0', accent: '#2e7d4f',
    props: ['lamp_rome', 'column', 'arch', 'cypress', 'fountain'],
    vehicle: 'vespa',
    landmarks: ['colosseum', 'trevi', 'pantheon'],
  },
];

export const LANDMARK_NAMES = {
  empire: 'Empire State Building', chrysler: 'Chrysler Building', brooklyn: 'Brooklyn Bridge',
  eiffel: 'Eiffel Tower', arc: 'Arc de Triomphe', louvre: 'Louvre Pyramid',
  bigben: 'Big Ben', towerbridge: 'Tower Bridge', eye: 'London Eye',
  colosseum: 'Colosseum', trevi: 'Trevi Fountain', pantheon: 'Pantheon',
};
